name: walkmoney
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  provider: ^4.3.1
  location: ^3.0.2
  latlong: ^0.6.1
  url_launcher: ^5.5.0
  audioplayers: ^0.15.1
  bordered_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: 8-bit
      fonts:
        - asset: fonts/8-bit.ttf
    - family: Custom
      fonts:
        - asset: fonts/Custom.ttf

